language: bash

sudo: required

os: linux
dist: xenial

services:
- docker

before_install:
# 升级 Docker 最新 stable
- docker --version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) ${DOCKER_CHANNEL}"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker --version
# 升级最新 Docker Compose
- docker-compose --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
# ubuntu 14.04
# - echo 'DOCKER_OPTS="--experimental"' | sudo tee /etc/default/docker
# - sudo service docker restart
# ubuntu 16.04
- sudo mkdir -p /etc/systemd/system/docker.service.d
- echo -e '[Service]\nExecStart=\nExecStart=/usr/bin/dockerd' | sudo tee /etc/systemd/system/docker.service.d/docker.conf
- echo '{"hosts":["unix:///var/run/docker.sock","tcp://0.0.0.0:2375"],"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo systemctl daemon-reload
- sudo systemctl cat docker
- sudo systemctl restart docker

script:
  - cp .env.example .env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker-compose build ${PHP_VERSION}
  - if [ -n "$UNIT" ];then docker build --target=php -t khs1994/php:${PHP_TAG_VERSION}-unit-alpine ${FOLDER}/unit; else docker build --target=php -t khs1994/php:${PHP_TAG_VERSION}-fpm-alpine ${FOLDER}/alpine; fi
after_success:
  - if [ -n "$UNIT" ];then docker push khs1994/php:${PHP_TAG_VERSION}-unit-alpine; else docker-compose push ${PHP_VERSION}; fi
  - curl -X POST https://hooks.microbadger.com/images/khs1994/php/OMVCEKSr9I0cjhU0DQop3HwjYAc=

branches:
  only:
  - master
  - dev

env:
  matrix:
  - PHP_VERSION=5_6_X FOLDER=5.6 PHP_TAG_VERSION=5.6.38
  - PHP_VERSION=7_0_X FOLDER=7.0 PHP_TAG_VERSION=7.0.32
  - PHP_VERSION=7_1_X FOLDER=7.1 PHP_TAG_VERSION=7.1.23
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.11
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.11 UNIT=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.0RC3
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly
  global:
  - DOCKER_COMPOSE_VERSION=1.22.0
  - DOCKER_BUILDKIT=1
  - DOCKER_CHANNEL=stable

matrix:
  fast_finish: true
  allow_failures:
  - env: PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.0RC3
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly
