version: "3.5"
services:

  7_2_X:
    build:
      context: ./7.2/alpine3.7
      args:
        PHP_VERSION: ${PHP_VERSION_72:-7.2.4}
        ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php-fpm:${PHP_VERSION_72:-7.2.4}-alpine3.7

  7_1_X:
    build:
      context: ./7.1/alpine3.4
      args:
        PHP_VERSION: ${PHP_VERSION_71:-7.1.16}
        # ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php-fpm:${PHP_VERSION_71:-7.1.16}-alpine3.4

  7_0_X:
    build:
      context: ./7.0/alpine3.4
      args:
        PHP_VERSION: ${PHP_VERSION_70:-7.0.29}
        # PHP_URL: http://cn2.php.net/get/php-${PHP_VERSION_70}.tar.xz/from/this/mirror
        # ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php-fpm:${PHP_VERSION_70:-7.0.29}-alpine3.4

  5_6_X:
    build:
      context: ./5.6/alpine3.4
      args:
        PHP_VERSION: ${PHP_VERSION_56:-5.6.35}
        # PHP_URL: http://cn2.php.net/get/php-${PHP_VERSION_56}.tar.xz/from/this/mirror
        # ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php-fpm:${PHP_VERSION_56:-5.6.35}-alpine3.4
